FROM openjdk:11
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ADD questionobjectionservice/target/questionObjectionService-0.0.1-SNAPSHOT.jar questionobjectionservice.jar
EXPOSE 9105
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar questionobjectionservice.jar"]
