FROM openjdk:11
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
#ENV JAVA_OPTS="$JAVA_OPTS -javaagent:/opt/prismo_agt_jdk11-v3.1.feat_b50.jar"
#ENV JAVA_OPTS="$JAVA_OPTS -Dprismo.agent.log_file=/opt/prismoagent_candidate-qbank.log"
#ENV JAVA_OPTS="$JAVA_OPTS -Dprismo_application_entity=\"CentOS7|Default Project|dex - candidate|Java 8|Engineering Org\\""
#ENV JAVA_OPTS="$JAVA_OPTS -Dprismo.agent.log_level=DEBUG -Dprismo_controller_host=3.109.8.238 -DPrismo_controller_port=7820 -Dprismo_collector_host=3.109.8.238 -Dprismo_include_host_id=false -Djdk.tls.client.protocols=TLSv1.2"
ADD questionbankservice/target/questionbankservice-0.0.1-SNAPSHOT.jar questionbankservice.jar
EXPOSE 8096
EXPOSE 5000
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar questionbankservice.jar"]
